server:
  port: 9629
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8 #????
          max-idle: 8  #??????
          min-idle: 0  #??????
          max-wait: 100ms  #??????

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  elasticsearch:
    uris: http://localhost:9200
#  canal:
#    instances:
#      example: # 拉取 example 目标的数据
#        host: localhost    # canal 所在机器的ip
#        port: 11111             # canal 默认暴露端口
#        user-name: canal        # canal 用户名
#        password: canal         # canal 密码
#        batch-size: 600         # canal 每次拉取的数据条数
#        retry-count: 5          # 重试次数,如果重试5次后,仍无法连接,则断开
#        cluster-enabled: false  # 是否开启集群
#       # zookeeper-address:      # zookeeper 地址(开启集群的情况下生效), 例: 192.168.0.1:2181,192.168.0.2:2181,192.168.0.3:2181
#        acquire-interval: 1000  # 未拉取到消息情况下,获取消息的时间间隔毫秒值
#        subscribe: .*\\..*      # 默认情况下拉取所有库、所有表
canal:
  destination: example
  server: 172.19.0.3:11111
  user-name: canal
  password: canal
  batch-size: 100
mybatis-flex:
  datasource:
    review:
      username: root
      password: 19990629
      url: jdbc:mysql://localhost:3307/review?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true&allowPublicKeyRetrieval=true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
knife4j:
  enable: true

minio:
  accessKey: root
  secretKey: 19990629
  #填写你的桶名称
  bucket: redis
  endpoint: http://localhost:9000
  readPath: http://localhost:9100
