---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2024/5/7 20:16
---
-- voucherId
local voucherId = tonumber(KEYS[1])
-- userId
local userId = tonumber(ARGV[1])
local orderId = tonumber(ARGV[2])
-- 键为当前优惠券，值为voucherVo
local killVoucherKey = 'redis:kill:voucher:' .. voucherId
--
-- 键为当前优惠券，值为使用该优惠券的userId
local killVoucherOrderKey = 'redis:order:' .. voucherId
--判断当前库存是否充足
if (tonumber(redis.call('hget', killVoucherKey, 'stock')) <= 0) then
    return 1
end
--判断该用户是否已使用该优惠券
if (redis.call('sismember', killVoucherOrderKey, userId) == 1) then
    return 2
end
--扣减库存
redis.call('hincrby', killVoucherKey, 'stock', -1)
--将下单用户放入使用该优惠券的集合中
redis.call('sadd', killVoucherOrderKey, userId)
redis.call('xadd', 'stream.order', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0